name: mobilab
description: Test app for Mobi Lab with lists management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.4.4
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.14.4

flutter:
  uses-material-design: true